[package]
name = "sio2"
version = "0.1.0"
authors = ["Dmitriy Shmilo <dmitriy.shmilo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.3.0"
rand = "0.7.2"
lazy_static = "1.4.0"